# roles/webserver/tasks/main.yml

---

- name: 1. install Apache
  apt: name=apache2 state=present
  
- name: 1.1 configurazione server name per localhost
  lineinfile:
        path: /etc/apache2/apache2.conf
        line: ServerName 127.0.0.1


- name: 3. start Apache
  service: name=apache2 state=started enabled=yes

