---
- name: 1. Install MySQLServer server package
  apt: name=mysql-server state=present

- name: 2. Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Install python Mysql package 
  apt: name=python3-mysqldb state=present
  
 



- name: 3. Create a new database
  mysql_db: 
    name: users 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: localhost  
    state: present 
  
  

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql
  
- name: Esegui il file SQL
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: localhost
    name: users
    state: import
    target: /tmp/dump.sql
    
- name: Create database user for php
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: localhost 
    name: php-user
    password: 12345
    priv: '*.*:ALL'
    state: present


- name: 6a. Install MySQL extension for PHP
  apt: name=php-mysql state=present

- name: 6b. Restart Apache
  service: name=apache2 state=restarted