---


- name: 1. Install MySQLServer server package
  apt: name=mysql-server state=present

- name: 2. Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Install python Mysql package 
  apt: name=python3-mysqldb state=present
  
 



- name: 3. Create a new database
  mysql_db: 
    name: "{{db_name }}"  
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: "{{db_host }}"   
    state: present 
  
  

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql
  
- name: Esegui il file SQL
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_host: "{{db_host }}" 
    name: "{{db_name }}"
    state: import
    target: /tmp/dump.sql
    

  
  
